include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/.symlinks/**
    - ios/Pods/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    unawaited_futures: true
